### ISSUE TITLE
Prometheus Datasource ``timeInterval`` not respected

### ISSUE THREAD

**Issue by Kariton** [remijouannet/graftorio2#17]
Hey ho,

Thanks for keeping this MOD alive!

But there is a issue with the default data source ``Scrape interval``.

``data/prometheus_datasource.yml`` 
```yml
apiVersion: 1

datasources:
  - name: prometheus
[...]
    url: http://prometheus:9090
    timeInterval: 10
```

should look like this:
```yml
apiVersion: 1

datasources:
  - name: prometheus
[...]
    url: http://prometheus:9090
    jsonData:
      timeInterval: '10s'
```
