### ISSUE TITLE
Electricity production/consumption

### ISSUE THREAD

**Issue by Tsuna77** [remijouannet/graftorio2#19]
Hello,

I do not found how to graph elecricity production/consumption, I using solar panel and want to check in grafana if everything goes right.

Is that me who do not find the good parameter, or do you need to update to add it ? (if update, I could try to help :))

**Comment by remijouannet** [comment]
salut, envoie moi ta save je vais regarder, c'est peut être un bug

**Comment by Tsuna77** [comment]
https://1drv.ms/u/s!AuK3D053xM_TjMZ7LHRDXZAHf-kcAw?e=xlMtM2 

Merci :)

**Comment by Tsuna77** [comment]
c'est une save qui viens d'un serveur, cela peut peut-être jouer ^^

**Comment by Tsuna77** [comment]
au cas ou voici la stack docker compose que j'utilise : 

```
factorio_1:
  image: factoriotools/factorio:1.1.61
  ports:
    - "34197:34197/udp"
  volumes:
   - /home/****/.config/factorio/data:/factorio
  restart: unless-stopped
  environment:
    - UID=1000
    - GID=1001
    - USERNAME=******
    - UPDATE_MODS_ON_START=true
    - TOKEN=********
    - INSTANCE_NAME="******"
    - INSTANCE_DESC="Instance 1"
exporter:
    image: prom/node-exporter
    command: --collector.textfile.directory=/textfiles
    restart: unless-stopped
    volumes:
      - /home/***/.config/factorio/data/script-output/graftorio2:/textfiles # Linux
    ports:
      - 9101:9100
      ```
